name: Update Voting Results

on:
  workflow_dispatch:  # Enables manual trigger
  schedule:
    - cron: "0 0 * * 0" # Weekly updates on Sunday

jobs:
  update-votes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install requests

    - name: Generate voting summary
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python3 community_labeling/src/update_community_labeling.py
      
    - name: Commit and push updates
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add community_labeling/voting_results/
        git commit -m "Update voting summary"
        git push
